### ISSUE TITLE
[Data Request]: Climate Data - Near-surface specific humidity

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#40]
### ID
near_surface_specific_humidity

### Description
Variable name - Near-surface specific humidity , as part of the Copernicus Climate Dataset

### Target Platform
Both (EOX and Rasdaman)

**Comment by KathiSchleidt** [comment]
@Mohinem am I correct in my assumption that this dataset (as well as [Rainfall Flux](https://github.com/FAIRiCUBE/data-requests/issues/42), [Near-surface wind speed](https://github.com/FAIRiCUBE/data-requests/issues/41)) are datasets that have been extended from [Climate data - Temperature](https://github.com/FAIRiCUBE/data-requests/issues/32)?

If so, I believe the other values provided for that dataset would also apply, could you please transfer the missing information? Otherwise we'll run into issues when we harvest the data request issues for provision of metadata!

**Comment by Mohinem** [comment]
Yes, correct, will add.

**Comment by pebau** [comment]
insufficient information provided, so closing. Feel free to file a [complete data request](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data).
