### ISSUE TITLE
project fields limitation

### ISSUE THREAD

**Issue by baloola** [FAIRiCUBE/data-requests#65]
Regarding the excel sheet approach were the issues should be created from the Invetory.xls file then stac items should be created.
I have mentioned running into a blocking issue regarding the fields limit.

The current state of the Inventory.xls file includes 74 fields (columns) for each item( issue). The idea of the script `project-update.py` is to generating project issues where each issue is representing its equivalent in the excel sheet.

The problem is that github provides the ability to have only 50 fields per issue. 

I have opened a question in the github community to follow up. https://github.com/orgs/community/discussions/66977 

@KathiSchleidt I would appreciate feedback about this.

**Comment by KathiSchleidt** [comment]
@baloola does this mean that the initial proposal by EOX to utilize GitHub for organization of dataset metadata for both ingestion and provision of metadata is not proving viable?

What does this mean for the final solution, where we've foreseen direct requests via GitHub? Assuming we have the same 50 field constraints?

Question: is is possible to also shift information to labels? Some fields like the requesting UC could be shifted to labels.
A few fields may still be dropped, as there are currently alternative approaches done by myself and @pebau I'm still waiting for resolution on.

Otherwise, if this remains an issue after we've dropped the inventory sheet, we may have to revert back to microformats for some of the fields after all (e.g. reverting the bbox to 1 encoded field in place of 4 individual values). If we do so, we must make sure that this is cleanly documented to avoid issues.

Looking forward to a proposal!

**Comment by pebau** [comment]
IMHO this system limitation is a kind reminder to us that we have left ground below our feet: nobody, really nobody will fill in such a number of fields one by one if left alone. Also BTW microformats would just increase the error rate for those who really dive into the dungeon.

After inspection of the sheet I found several redundancies, but eliminating them would not reduce the overall number dramatically.

BTW: just counted, the datacube-related items are 16.

I am still convinced, as WP6 lead, that we need to guide our UCs and have crisp meetings where we help them filling in, spreadsheet or github form. And we need to be very greedy with the fields - on the side, it is a typical hunger of administration to collect all sort of information "just in case". Our challenge will be to find a wise selection.

**Comment by KathiSchleidt** [comment]
@pebau when I count, I find 36 columns under Datacube description. This is excluding details such as name.

As you've regularly complained as to the proposed metadata fields, please provide feedback on which ones you deem unnecessary! Only complaining doesn't help anybody :(

**Comment by KathiSchleidt** [comment]
@baloola in order to move on here, I've reverted to some microformats (extents, both bbox and lower/upper bounds). In addition, I've removed quite a few of the metadata columns, as either currently not relevant for external data sources (explicit provenance information, Accessibility) or too poorly specified in D4.2 (data quality). Finally, I've reduced the date fields to 1 field.

With these reductions, think you can squeeze under the 50 field limit (you'll probably have to merge the ingestion relevant information (which UC/SW Stack) into one field while dropping Ingestion Status (should be in the GitHub issue)

I would like to have a proposal from EOX for:
- adding the currently dropped information to the metadata, without too much additional burden to UC
- how the actual process will work, assuming we're still stuck with the 50 field limitation? I do wonder if the proposal to use GitHub for this purpose was actually a good decision :(

**Comment by KathiSchleidt** [comment]
PS: forgot to mention, the update is now in [Inventory3](https://nilu365.sharepoint.com/:x:/r/sites/Horizon2021_CUBE/Shared%20Documents/WP2%20-%20use/DataLayerInventory/Inventory_V3.xlsx?d=w8ada1b8c243b469d928864bbc24f95aa&csf=1&web=1&e=TNG1Nb) as I didn't want to loose the currently removed fields

**Comment by pebau** [comment]
> PS: forgot to mention, the update is now in [Inventory3](https://nilu365.sharepoint.com/:x:/r/sites/Horizon2021_CUBE/Shared%20Documents/WP2%20-%20use/DataLayerInventory/Inventory_V3.xlsx?d=w8ada1b8c243b469d928864bbc24f95aa&csf=1&web=1&e=TNG1Nb) as I didn't want to loose the currently removed fields

the one to be used remains v2. Everything else is not agreed with the WP5 lead. We will stick with v2 until each single change over v2 is documented, motivated, and agreed with the WP5 lead.

**Comment by pebau** [comment]
did we solve this issue? IMHO yes, as the Web GUI is going into production now meaning we have an agreement on the fields.

Therefore, suggest closing it.
