### ISSUE TITLE
Climate extremes indices and heat stress indicators

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#70]

**Comment by Mohinem** [comment]
@robknapen @capoony 

Here is the website-
https://cds.climate.copernicus.eu/cdsapp#!/dataset/sis-extreme-indices-cmip6?tab=form

There are multiple options in the 'Download Data' section, and I would like someone to tell me all of them.

The options I am interested are-

1. Variable
a. Extreme value indices (ETCCDI)
b. Heat stress indicators(HSI)

2. Product type
a. ETCCDI
b. HSI

3. Model
4. Ensemble Member

5. Experiment

6. Temporal Aggregation

7. Period

8. Version (by default I select 2.0, if anything else is required, please inform).

**Comment by robknapen** [comment]
Hi, I don't think this dataset is of primary use for our use case. So I will remove myself from the assigned list.

**Comment by sonjastndl** [comment]
Hi @Mohinem
I would suggest the following: 
1a. ETCCDI: Cold days, consecutive wet days, extremely wet day precipitation, growing seasno length, min value daily max temp, min value daily min temp, warm days, cold nights, consecutive dry days, frost days, summer days, tropical nights , warm nights 

1b.HSI: all

2a. Product Type: base independent I guess since our time span is not offered
2b. I don't know? Can someone explain how the bias adjustment works and what bias this accounts for?

3. I assume EC-Earth3 (Europe), GFDL-CM4 (USA)
4. I don't know, what would you suggest?
5. All
6. Daily
7. 19510101-20141231 , 20150101-21001231



@capoony Please add something you find to be of use or correct me if some are not needed :)

**Comment by pebau** [comment]
seems from this discussion key insights are still missing; please file a  [standard data-request issue](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data) containing all information agreed. Happy also to have a telco to allow clarification of all necessary details.

Closing this issue for now.
