### ISSUE TITLE
KPIs on agricultural land management 

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#76]

**Comment by Mohinem** [comment]
On the inventory (https://nilu365.sharepoint.com/:x:/r/sites/Horizon2021_CUBE/_layouts/15/Doc.aspx?sourcedoc=%7B8c509b96-28d4-4644-8d1b-08c407c349de%7D), it mentions that the data is restricted. Please help me find a way to retrieve the data, and provide further details (mostly temporal, like time resolution, interval etc.) to start the ingestion process.

**Comment by robknapen** [comment]
This dataset and the UC2 approach related to obtaining information about agricultural land management practices needs to be reconsidered, since we were not able to obtain access to the farmer specific detailed KPI information. This currently requires a consent from each individual farmer, which has turned out to be infeasible within this project. So we need e.g. proxy KPI data, synthesised training data, or something similar.

**Comment by pebau** [comment]
ok, so closing the issue.
