### ISSUE TITLE
Actual height database (AHN)

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#79]

**Comment by Mohinem** [comment]
There is a nice website, and a nice viewer-

https://www.ahn.nl/ahn-viewer

There are many layers as well.

Please inform me which layers to ingest and I start downloading them.

**Comment by KathiSchleidt** [comment]
I can make your life a bit easier, we set up this dataset for RWS a while back:
https://coverage.wetransform.eu/rws/hoogte_nl_1m/2023-08/ows

@robknapen what resolution would you like? Starts at 1m, goes up by powers of 2

**Comment by robknapen** [comment]
For use case 2 the most likely usage of elevation data is for the species distribution modelling (gap filling / biodiversity estimation), so we will need it at a matching resolution with all the other covariates. I.e. 10m or 100m in LAEA projection (EPSG 3035).

**Comment by Mohinem** [comment]
2 comments here - 

1. If resolution starts at 1m and goes by powers of 2, achieving 10 m resolution is not possible as 10 is not a power of 2.
2. How do I download the dataset ? I am not understanding the things written in Dutch.

**Comment by KathiSchleidt** [comment]
@Mohinem where in the WCS I provided for you is Dutch an issue?
Also, with elevation data, you can cleanly interpolate, this should allow you to both transform the existing EPSG:4258 grid to EPSG:3035 as well as transforming 1m resolution to 10m.

If your issue is that you don't trust the alternative source I've provided, I consulted for Rijkswaterstaat (RWS) a few years ago on this topic, wetransform then implemented utilizing rasdaman, reason its running on a wetransform URI. This is the definitive source data available in NL.

**Comment by Mohinem** [comment]
@KathiSchleidt  I asked my colleagues, they told me that we don't maintain this particular rasdaman service. I cannot run a GetRequest to fetch the TIFF files, it shows an error message. So I can't download this data to my machine, and then ingest it to the Fairicube Rasdaman instance.

**Comment by KathiSchleidt** [comment]
@Mohinem 
While I also had an issue accessing data directly via the rasdaman GUI, when I try via the following URI, I get a TIF file:
https://coverage.wetransform.eu/rws/hoogte_nl_1m/2023-08/ows?&SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=hoogte_nl_1m&SUBSET=Lat(50.7,50.8)&SUBSET=Lon(3.3,3.4)&FORMAT=image/tiff

If there are issues, please report them, and I'll get in touch with RWS to sort this. As a final fall-back option, I'm pretty sure we can get direct access to the TIF files

**Comment by vittekm** [comment]
Hi @Mohinem, I created download link for OHN dataset which is derived from AHN and made from original point cloud data. While AHN is absolute height (above sea level), OHN is object heigh (e.g. trees, buildings height) which is more relevant for our use case. We use this file to when creating Dutch land use dataset and resolution is 0.5 m. I think the best is to ingest this dataset and likely we will not need then AHN.
https://filesender.surf.nl/?s=download&token=a34243d5-a9d5-4a18-a162-cef8c5b03ad7

**Comment by Mohinem** [comment]
Thanks @vittekm , I have finally downloaded the dataset.

Question-
Is there a time information associated with the dataset, that I need to add while ingestion ? Or not ? I will have to document either situation.

**Comment by vittekm** [comment]
Hi @Mohinem, there is not time information for dataset as whole. Data were acquired for different regions within Netherlands in different years. But situation when dataset was downloaded with most recent data is year 2022.

**Comment by Mohinem** [comment]
hi @vittekm , in that case I can start ingestion without putting time information, as it doesn't make sense for me otherwise. Please confirm if that's fine with you.

**Comment by vittekm** [comment]
Hi @Mohinem I think it will be fine when you give year 2022 as a time infortmation. So with that the dataset is ready for ingestion.

**Comment by Mohinem** [comment]
Hi @vittekm , looks like the file I have downloaded is corrupt :'(. Is it possible for you to send a new download link ?

**Comment by pebau** [comment]
following this discussion I see that we suffer from not following the [standard procedure](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data). Therefore, and because at the last user meeting it was stated that all datasets currently requried are available, l closing this issue. Feel free to [create a data-request issue with all relevant information](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data).
