### ISSUE TITLE
Vegetation Indexes (TBD)

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#85]

**Comment by KathiSchleidt** [comment]
@sonjastndl maybe take a closer look at the available sources, e.g. [NVDI available from Copernicus](https://land.copernicus.eu/global/products/ndvi)

**Comment by sonjastndl** [comment]
> @sonjastndl maybe take a closer look at the available sources, e.g. [NVDI available from Copernicus](https://land.copernicus.eu/global/products/ndvi)

I would need some more understanding of this characteristics table. Having some first looks on the provided information, I would say the NDVI 1km Data might be of interest from Jan 199-June 2020 (biggest time span), SPOT/VEGATATION & PROBA-V (because if it has both data why not), but what does "Timeliness" "Archive only mean"? Other datasets also include "annual".
Are there any differences between the Platforms/Sensors, since the catch different values and delivery different products, which one is used more often?


NDVI is mostly used in crop studies, to determine plant health or to distinguish between soil and very dense vegatation right?
If anyone has a good source on possible classifications of land-type based on NDVI, that might be very useful :)

**Comment by KathiSchleidt** [comment]
@sonjastndl I think Bernadett's presentation from today's data science seminar could help you understand the various vegetation indexes - she just skipped over the relevant slides, but we'll surely get the presentation soon

**Comment by sonjastndl** [comment]
> @sonjastndl I think Bernadett's presentation from today's data science seminar could help you understand the various vegetation indexes - she just skipped over the relevant slides, but we'll surely get the presentation soon

Had the same thought! :)

**Comment by pebau** [comment]
following discussion here, please feel free to [file a data-request issue](https://github.com/FAIRiCUBE/data-requests/wiki/How-to-Add-Data) for whatever additional data you require. Closing this issue.
