### ISSUE TITLE
[Data Request]: Water and Wetness

### ISSUE THREAD

**Issue by Mohinem** [FAIRiCUBE/data-requests#9]
### ID

water_and_wetness

### Description

A time series data of type of water bodies in the EEA39 area.

### Target Platform

Rasdaman

### Preferred Method

Assisted by the platform provider

### Axes

Lat, Long: horizontal extent - Europe; 
regular, resolution: 10m, uom: metre 

T: time, axis inserted to create time series database; 
     Time slice - "2018-01-01T20:12:02”; 
     lower bound same as upper bound 

### Cell type

8-bit integer denoting the type of water body.
0 - Dry
1 - Permanent water
2 - Temporary water
3 - Permanent wet
4 - Temporary wet
253 - Sea water
254 - Unclassifiable
355 - outside area

### Null values

254 - unclassifiable, 255 - outside area

### (Meta) data Standards

standards data complies with Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services, Date of publication: 2010-12-08

### APIs

OGC WMS, WCS, WCPS

### Access control

login-protected, access only for FAIRiCUBE beneficiaries

### Responsible

Constructor University, mbasak@constructor.university

### Data Source

Origin of data – EEA, URL -- https://land.copernicus.eu/pan-european/high-resolution-layers/water-wetness/status-maps/water-wetness-2018?tab=download

### Data Preprocessing

None in particular

### Quality Control

Quality assurance followed the ISO9001 standards for Quality Management and the INSPIRE data quality elements

### Documents & publications

None

### License

License Link - https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32013R1159

### Ownership

EEA

### Personal Data

No personal data are captured in this datacube

**Comment by KathiSchleidt** [comment]
same as #39

**Comment by KathiSchleidt** [comment]
@Mohinem @pebau I've now seen the additional water_and_wetness_2015 coverage you've added. Comments:
- Any reason the original water_and_wetness (2018 data) is still provided converted to WGS84 (with an eclectic mix of CRS in EPSG 4326, GridEnvelope in EPSG:3035 (original CRS))? I still see this as an error.
- Any reason you provide different temporal intervals:
  - 2015: ["2014-12-31T12:00:00.000Z", "2015-01-01T12:00:00.000Z"]
  - 2018: ["2018-01-01T08:12:02.000Z", "2018-01-02T08:12:02.000Z"]
- Assuming that aspects such as the rangeType description and the link to metadata will be added at a later date?

**Comment by pebau** [comment]
>     * Any reason you provide different temporal intervals:
>       
>       * 2015: ["2014-12-31T12:00:00.000Z", "2015-01-01T12:00:00.000Z"]
>       * 2018: ["2018-01-01T08:12:02.000Z", "2018-01-02T08:12:02.000Z"]

well, data have a delivery date in the dataset, and that we used naively. Following further discussion we will replace with integer years, so no more concerns.

>     * Assuming that aspects such as the rangeType description and the link to metadata will be added at a later date?

I am *not* going to repeat a 3rd time here, see other issues with the same question.

**Comment by KathiSchleidt** [comment]
@pebau now I'm really impressed!!! They manage to deliver the 2018 dataset at the start of the year? How did they generate this in advance?

**Comment by pebau** [comment]
Recall the outcome of the discussion (BTW, cannot find the minutes): validity is the year of publication.

**Comment by KathiSchleidt** [comment]
@pebau let me think this through. For the 2015 dataset, the raw data is collected in the course of 2015. However, in order to derive the Water and Wetness values, post-processing is required on the entire dataset. As the 2015 dataset is not complete until the end of 2015, the post-processing cannot commence until the start of 2016, implying that the year of publication MUST be after 2015, the year for which the data is representative.

This also becomes clear when one peruses the metadata provided for this dataset. Looking at Water and Wetness 2015, I find all sorts of dates:

- Source Data: 2009 to 2015
- Date for which data is seen as valid: 2015
- Creation Date: 2018-03-22
- Publication Date: 2018-03-22
- Revision Date: 2020-11-19

_Note: this is the reason we have multiple dates in OMS_

Utilizing the publication date as you propose doesn't really make sense with such processed data only available several years after the actual phenomenon the data is describing (what's missing on all sides is what we call phenomenonTime in OMS)

Could you please explain why the 2015 dataset indicates validity from 2014-12-31T12:00:00.000Z - 2015-01-01T12:00:00.000Z
